name: "Build iOS IPA"

on:
  workflow_dispatch: # Esto te permite ejecutarlo manualmente desde GitHub

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest # Aquí es donde ocurre la magia (usa una Mac de GitHub)
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build IPA
        run: flutter build ipa --no-codesign # Genera el archivo sin firma (para pruebas rápidas)

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
